_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderGDrive
  file_id: 19h3kqar1wlELAmM5hDyj9tlrUh8yjrCl
  path_local: /opt/facetorch/models/torchscript/predictor/embed/1/model.pt # str

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [244, 244] # List[int]
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406] # List[float]
        std: [0.228, 0.224, 0.225] # List[float]
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.embed.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostEmbedder
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.embed.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["abstract"] # List
