
_target_: facetorch.analyzer.utilizer.align.Lmk3DMeshPose
transform: None
device:
  _target_: torch.device
  type: ${analyzer.device} # str
optimize_transform: False
downloader_meta:
  _target_: facetorch.downloader.DownloaderGDrive
  file_id: 11tdAcFuSXqCCf58g52WT1Rpa8KuQwe2o  # str
  path_local: ${facetorch.metadata_dir:}/3dmm/meta.pt # str
  revision: gdrive-file-11tdAcFuSXqCCf58g52WT1Rpa8KuQwe2o
  sha256: db957f82e4c85884c3d9bb4e49469e3caf1e5b488c4cb3b72888e75a71c77890
  size_bytes: 33211475
  expected_format: torch_data
  offline: ${offline}
image_size: 120
