_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderHuggingFace
  file_id: 16gNFQdEH2nWvW3zTbdIAniKIbPAp6qBA
  path_local: ${facetorch.model_dir:}/exported/predictor/align/1/model.pt2 # str
  repo_id: tomas-gajarsky/facetorch-align-synergynet  # HuggingFace repo ID
  manifest_id: align-synergynet
  revision: 364645b1201b0a418a91d52cf420c33a29cb2f17
  offline: ${offline}
  allow_legacy_models: ${allow_legacy_models}
  device: ${analyzer.device}

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [120, 120] # List[int]
        antialias: True # bool
  device:
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostEmbedder
  transform: None
  device:
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["abstract"] # List
