services:

  facetorch:
    image: "tomasgajarsky/facetorch:${FACETORCH_DOCKER_TAG:-1.0.0-rc.3}"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - facetorch-cache-cpu:/var/cache/facetorch
      - ./data/input:/workspace/data/input:ro
      - facetorch-output:/workspace/data/output
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch

  facetorch-gpu:
    image: "tomasgajarsky/facetorch-gpu:${FACETORCH_DOCKER_TAG:-1.0.0-rc.3}"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - facetorch-cache-gpu:/var/cache/facetorch
      - ./data/input:/workspace/data/input:ro
      - facetorch-output:/workspace/data/output
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  facetorch-gpu-no-device:
    image: "tomasgajarsky/facetorch-gpu:${FACETORCH_DOCKER_TAG:-1.0.0-rc.3}"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - facetorch-cache-gpu:/var/cache/facetorch
      - ./data/input:/workspace/data/input:ro
      - facetorch-output:/workspace/data/output
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch

volumes:
  facetorch-cache-cpu:
  facetorch-cache-gpu:
  facetorch-output:
