services:

  facetorch:
    image: tomasgajarsky/facetorch:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - facetorch-cache-cpu:/var/cache/facetorch
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch
    entrypoint: [ "/bin/bash" ]

  facetorch-gpu:
    image: tomasgajarsky/facetorch-gpu:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - facetorch-cache-gpu:/var/cache/facetorch
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: [ "/bin/bash" ]

  facetorch-gpu-no-device:
    image: tomasgajarsky/facetorch-gpu:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - facetorch-cache-gpu:/var/cache/facetorch
    environment:
      FACETORCH_CACHE_DIR: /var/cache/facetorch
    entrypoint: [ "/bin/bash" ]

volumes:
  facetorch-cache-cpu:
  facetorch-cache-gpu:
