name: env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - codetiming>=1.2.0
  - cuda-version=12.4
  - googleapis-common-protos>=1.56.3
  - gdown>=3.11.0
  - hydra-core>=1.0.0
  - numpy>=1.18.2
  - pip>=20.0.2
  - python-json-logger>=2.0.0
  - pytorch-gpu>=2.3.0
  - requests>=2.20.0
  - timm>=0.6.0
  - torchvision>=0.15.0
  - huggingface_hub>=0.16.0
