name: env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - codetiming>=1.2.0
  - cudatoolkit=11.2.2
  - googleapis-common-protos>=1.56.3
  - gdown>=3.11.0
  - hydra-core>=1.0.0
  - numpy>=1.18.2
  - pip>=20.0.2
  - python-json-logger>=2.0.0
  - pytorch-gpu>=1.9.0, <1.12
  - torchvision>=0.10.0, <0.13.0
  - huggingface_hub>=0.16.0