analyzer:
  device: cpu
  optimize_transforms: true
  utilizer_dependencies:
    align:
    - align
  reader:
    _target_: facetorch.analyzer.reader.UniversalReader
    device:
      _target_: torch.device
      type: ${analyzer.device}
    optimize_transform: ${analyzer.optimize_transforms}
    max_decoded_pixels: 16777216
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _target_: facetorch.transforms.SquarePad
      - _target_: torchvision.transforms.Resize
        size:
        - 1080
        antialias: true
  detector:
    _target_: facetorch.analyzer.detector.FaceDetector
    downloader:
      _target_: facetorch.downloader.DownloaderHuggingFace
      file_id: 1eMuOdGkiNCOUTiEbKKoPCHGCuDgiKeNC
      path_local: ${facetorch.model_dir:}/exported/detector/1/model.pt2
      repo_id: tomas-gajarsky/facetorch-detector-retinaface
      manifest_id: detector-retinaface
      revision: b4240f23442f52dae9de2ecee8fd279a2ca4545d
      offline: ${offline}
      allow_legacy_models: ${allow_legacy_models}
      device: ${analyzer.device}
    device:
      _target_: torch.device
      type: ${analyzer.device}
    preprocessor:
      _target_: facetorch.analyzer.detector.pre.DetectorPreProcessor
      transform:
        _target_: torchvision.transforms.Compose
        transforms:
        - _target_: torchvision.transforms.Normalize
          mean:
          - 123.0
          - 117.0
          - 104.0
          std:
          - 1.0
          - 1.0
          - 1.0
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: ${analyzer.optimize_transforms}
      reverse_colors: true
    postprocessor:
      _target_: facetorch.analyzer.detector.post.PostRetFace
      transform: None
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: ${analyzer.optimize_transforms}
      confidence_threshold: 0.02
      top_k: 5000
      nms_threshold: 0.4
      keep_top_k: 750
      score_threshold: 0.6
      prior_box:
        _target_: facetorch.analyzer.detector.post.PriorBox
        min_sizes:
        - - 16
          - 32
        - - 64
          - 128
        - - 256
          - 512
        steps:
        - 8
        - 16
        - 32
        clip: false
      variance:
      - 0.1
      - 0.2
      expand_box_ratio: 0.0
  unifier:
    _target_: facetorch.analyzer.unifier.FaceUnifier
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.0
        - 0.0
        - 0.0
        std:
        - 255.0
        - 255.0
        - 255.0
      - _target_: torchvision.transforms.Resize
        size:
        - 380
        - 380
        antialias: true
    device:
      _target_: torch.device
      type: ${analyzer.device}
    optimize_transform: ${analyzer.optimize_transforms}
  predictor:
    embed:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 19h3kqar1wlELAmM5hDyj9tlrUh8yjrCl
        path_local: ${facetorch.model_dir:}/exported/predictor/embed/1/model.pt2
        repo_id: tomas-gajarsky/facetorch-embed-resnet-50
        manifest_id: embed-resnet50
        revision: 5df1ddec26010a64ad7bc8cea717997c71238923
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 244
            - 244
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.485
            - 0.456
            - 0.406
            std:
            - 0.228
            - 0.224
            - 0.225
        device:
          _target_: torch.device
          type: ${analyzer.predictor.embed.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostEmbedder
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.embed.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        labels:
        - abstract
    verify:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 1WI-mP_0mGW31OHfriPUsuFS_usYh_W8p
        path_local: ${facetorch.model_dir:}/exported/predictor/verify/2/model.pt2
        repo_id: tomas-gajarsky/facetorch-verify-adaface
        manifest_id: verify-adaface
        revision: 62b32103fa1b1d7e08943ff20801d14de73101c1
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 112
            - 112
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.5
            - 0.5
            - 0.5
            std:
            - 0.5
            - 0.5
            - 0.5
        device:
          _target_: torch.device
          type: ${analyzer.predictor.verify.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: true
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostEmbedder
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.verify.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        labels:
        - abstract
    fer:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 1xoB5VYOd0XLjb-rQqqHWCkQvma4NytEd
        path_local: ${facetorch.model_dir:}/exported/predictor/fer/2/model.pt2
        repo_id: tomas-gajarsky/facetorch-fer-efficientnet-b2
        manifest_id: fer-efficientnet-b2
        revision: 18c1748e14ed6e353eb88cea7e01bf8da9f6de4c
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 260
            - 260
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.485
            - 0.456
            - 0.406
            std:
            - 0.229
            - 0.224
            - 0.225
        device:
          _target_: torch.device
          type: ${analyzer.predictor.fer.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostArgMax
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.fer.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        dim: 1
        labels:
        - Anger
        - Contempt
        - Disgust
        - Fear
        - Happiness
        - Neutral
        - Sadness
        - Surprise
    au:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 1uoVX9suSA5JVWTms3hEtJKzwO-CUR_jV
        path_local: ${facetorch.model_dir:}/exported/predictor/au/1/model.pt2
        repo_id: tomas-gajarsky/facetorch-au-opengraph
        manifest_id: au-opengraph
        revision: 016e8b39233d50271e1881281c1a9f7b366d7947
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 224
            - 224
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.485
            - 0.456
            - 0.406
            std:
            - 0.229
            - 0.224
            - 0.225
        device:
          _target_: torch.device
          type: ${analyzer.predictor.au.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostMultiLabel
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.au.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        dim: 1
        threshold: 0.5
        labels:
        - inner_brow_raiser
        - outer_brow_raiser
        - brow_lowerer
        - upper_lid_raiser
        - cheek_raiser
        - lid_tightener
        - nose_wrinkler
        - upper_lip_raiser
        - nasolabial_deepener
        - lip_corner_puller
        - sharp_lip_puller
        - dimpler
        - lip_corner_depressor
        - lower_lip_depressor
        - chin_raiser
        - lip_pucker
        - tongue_show
        - lip_stretcher
        - lip_funneler
        - lip_tightener
        - lip_pressor
        - lips_part
        - jaw_drop
        - mouth_stretch
        - lip_bite
        - nostril_dilator
        - nostril_compressor
        - left_inner_brow_raiser
        - right_inner_brow_raiser
        - left_outer_brow_raiser
        - right_outer_brow_raiser
        - left_brow_lowerer
        - right_brow_lowerer
        - left_cheek_raiser
        - right_cheek_raiser
        - left_upper_lip_raiser
        - right_upper_lip_raiser
        - left_nasolabial_deepener
        - right_nasolabial_deepener
        - left_dimpler
        - right_dimpler
    va:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 1Xl4ilNCU_DgKNhITrXb3UyQUUdm3VTKS
        path_local: ${facetorch.model_dir:}/exported/predictor/va/1/model.pt2
        repo_id: tomas-gajarsky/facetorch-va-elim
        manifest_id: va-elim
        revision: 4e6f4909f9f36d5f0f807f2181093d03a494c5b8
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 224
            - 224
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.485
            - 0.456
            - 0.406
            std:
            - 0.229
            - 0.224
            - 0.225
        device:
          _target_: torch.device
          type: ${analyzer.predictor.va.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostLabelConfidencePairs
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.va.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        labels:
        - valence
        - arousal
        offsets:
        - 0
        - 0
    deepfake:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 1GjDTwQpvrkCjXOdiBy1oMkzm7nt-bXFg
        path_local: ${facetorch.model_dir:}/exported/predictor/deepfake/1/model.pt2
        repo_id: tomas-gajarsky/facetorch-deepfake-efficientnet-b7
        manifest_id: deepfake-efficientnet-b7
        revision: a0c23dffebb927d6f3651ab1210fac3f27a0cbfa
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 380
            - 380
            antialias: true
          - _target_: torchvision.transforms.Normalize
            mean:
            - 0.485
            - 0.456
            - 0.406
            std:
            - 0.229
            - 0.224
            - 0.225
        device:
          _target_: torch.device
          type: ${analyzer.device}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostSigmoidBinary
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.device}
        optimize_transform: ${analyzer.optimize_transforms}
        labels:
        - Real
        - Fake
        threshold: 0.7
    align:
      _target_: facetorch.analyzer.predictor.FacePredictor
      downloader:
        _target_: facetorch.downloader.DownloaderHuggingFace
        file_id: 16gNFQdEH2nWvW3zTbdIAniKIbPAp6qBA
        path_local: ${facetorch.model_dir:}/exported/predictor/align/1/model.pt2
        repo_id: tomas-gajarsky/facetorch-align-synergynet
        manifest_id: align-synergynet
        revision: 807894a3a00396658f7c538cbb5fb8e55980755c
        offline: ${offline}
        allow_legacy_models: ${allow_legacy_models}
        device: ${analyzer.device}
      device:
        _target_: torch.device
        type: ${analyzer.device}
      preprocessor:
        _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
          - _target_: torchvision.transforms.Resize
            size:
            - 120
            - 120
            antialias: true
        device:
          _target_: torch.device
          type: ${analyzer.predictor.align.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        reverse_colors: false
      postprocessor:
        _target_: facetorch.analyzer.predictor.post.PostEmbedder
        transform: None
        device:
          _target_: torch.device
          type: ${analyzer.predictor.align.device.type}
        optimize_transform: ${analyzer.optimize_transforms}
        labels:
        - abstract
  utilizer:
    align:
      _target_: facetorch.analyzer.utilizer.align.Lmk3DMeshPose
      transform: None
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: false
      downloader_meta:
        _target_: facetorch.downloader.DownloaderGDrive
        file_id: 11tdAcFuSXqCCf58g52WT1Rpa8KuQwe2o
        path_local: ${facetorch.metadata_dir:}/3dmm/meta.pt
        revision: gdrive-file-11tdAcFuSXqCCf58g52WT1Rpa8KuQwe2o
        sha256: db957f82e4c85884c3d9bb4e49469e3caf1e5b488c4cb3b72888e75a71c77890
        size_bytes: 33211475
        expected_format: torch_data
        offline: ${offline}
      image_size: 120
    draw_boxes:
      _target_: facetorch.analyzer.utilizer.draw.BoxDrawer
      transform: None
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: false
      color: green
      line_width: 3
    draw_landmarks:
      _target_: facetorch.analyzer.utilizer.draw.LandmarkDrawerTorch
      transform: None
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: false
      width: 2
      color: green
    save:
      _target_: facetorch.analyzer.utilizer.save.ImageSaver
      transform: None
      device:
        _target_: torch.device
        type: ${analyzer.device}
      optimize_transform: false
  logger:
    _target_: facetorch.logger.LoggerJsonFile
    name: facetorch
    level: 20
    path_file: null
    json_format: '%(asctime)s %(levelname)s %(message)s'
main:
  sleep: 3
debug: true
offline: ${facetorch.offline:}
allow_legacy_models: false
path_image: null
batch_size: 8
fix_img_size: true
include_tensors: true
path_output: null
path_image_2: null
