_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderHuggingFace
  file_id: 16gNFQdEH2nWvW3zTbdIAniKIbPAp6qBA
  path_local: /opt/facetorch/models/torchscript/predictor/align/1/model.pt # str
  repo_id: tomas-gajarsky/facetorch-align-synergynet  # HuggingFace repo ID
  filename: model.pt  # Filename in the HuggingFace repo

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [120, 120] # List[int]
        antialias: True # bool
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostEmbedder
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["abstract"] # List
