_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderHuggingFace
  file_id: 1WI-mP_0mGW31OHfriPUsuFS_usYh_W8p
  path_local: /opt/facetorch/models/exported/predictor/verify/2/model.pt2 # str
  repo_id: tomas-gajarsky/facetorch-verify-adaface  # HuggingFace repo ID
  filename: model.pt2  # Filename in the HuggingFace repo
  export_filenames_by_torch_minor:
    "2.3": model-torch2.3.pt2
    "2.6": model-torch2.6.pt2
    "2.11": model-torch2.11.pt2

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize        
        size: [112, 112] # List[int]
        antialias: True # bool
      - _target_: torchvision.transforms.Normalize
        mean: [0.5, 0.5, 0.5] # List[float]
        std: [0.5, 0.5, 0.5] # List[float]
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.verify.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  reverse_colors: True # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostEmbedder
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.verify.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["abstract"] # List
