_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderHuggingFace
  file_id: 1GjDTwQpvrkCjXOdiBy1oMkzm7nt-bXFg
  path_local: /opt/facetorch/models/torchscript/predictor/deepfake/1/model.pt # str
  repo_id: tomas-gajarsky/facetorch-deepfake-efficientnet-b7  # HuggingFace repo ID
  filename: model.pt  # Filename in the HuggingFace repo

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize        
        size: [380, 380] # List[int]
        antialias: True # bool
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406] # List[float]
        std: [0.229, 0.224, 0.225] # List[float]
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.deepfake.device.type}
  optimize_transform: ${analyzer.optimize_transforms} # bool
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostSigmoidBinary
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.deepfake.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["Real", "Fake"] # List
  threshold: 0.7
