
_target_: facetorch.analyzer.utilizer.draw.LandmarkDrawer
transform: None
device:
  _target_: torch.device
  type: ${analyzer.device} # str
optimize_transform: False
marker: o
markersize: 0.9
alpha: 0.8
line_width: 0.8
color: g
markeredgecolor: green