name: conda-env

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: "3.10"
          environment-file: environment.yml
          activate-environment: base
          auto-activate-base: true

      - name: Install facetorch from conda-forge
        run: |
          conda install -c conda-forge facetorch
